// src/constant/events.ts
export const CHAT_JOINED = "CHAT_JOINED";
export const CHAT_LEAVED = "CHAT_LEAVED";
export const NEW_MESSAGE = "NEW_MESSAGE";
export const NEW_MESSAGE_ALERT = "NEW_MESSAGE_ALERT";
export const NEW_NOTIFICATION_ALERT = "NEW_NOTIFICATION_ALERT";
export const NEW_REACTION = "NEW_REACTION";
export const ONLINE_USERS = "ONLINE_USERS";
export const DELETE_MESSAGE = "DELETE_MESSAGE";
export const UPDATE_LAST_MESSAGE = "UPDATE_LAST_MESSAGE";
export const START_TYPING = "START_TYPING";
export const STOP_TYPING = "STOP_TYPING";
export const UPDATE_MESSAGE = "UPDATE_MESSAGE";
